[project]
name = "cv"
version = "0.2.0"
description = ""
authors = [{ name = "Kenneth V. Domingo", email = "hello@kvd.studio" }]
requires-python = "~=3.12.0"
readme = "README.md"
dependencies = ["rendercv~=1.14"]
