version: '3'

tasks:
  default:
    cmd:
      task: render

  render:
    cmd: uv run rendercv render Kenneth_V._Domingo_CV.yaml
    sources:
      - Kenneth_V._Domingo_CV.yaml
      - classic/*
      - markdown/*
    generates:
      - rendercv_output/*
    watch: true
